### ISSUE TITLE
Calculate image file system layout dynamically

### ISSUE THREAD

**Issue by K3rm1t4** [limepepper/raspberry-pi-factory-reset#1]
Eliminating [hard-coded values in file system generation](https://github.com/limepepper/ansible-role-raspberrypi/blob/master/files/create-factory-reset#L55) code has already been mentioned as a possible enhancement in your blog post.

Any estimation when there will be time to implement this?
This change would be very much appreciated, opening the door for usage of more recent and future Raspbian versions.

**Comment by tolland** [comment]
I'm glad that there was some interest!

I'll put it on the list to look at this week...

**Comment by K3rm1t4** [comment]
Definitely, I think it's a great idea - even though I have to admit my use case is a rather small one (home environment, 2 RPis, no Ansible).

While you're at it pushing updates, maybe you'd like to take a look at the following:
At least tune2fs version 1.44.2 (14-May-2018) seems to have issues with syntax of commands [#103](https://github.com/limepepper/ansible-role-raspberrypi/blob/74020a705f7d7d65414d2e2bfbdbfe638059bb90/files/create-factory-reset#L103) and [#104](https://github.com/limepepper/ansible-role-raspberrypi/blob/74020a705f7d7d65414d2e2bfbdbfe638059bb90/files/create-factory-reset#L104), expecting partition information as the last argument now:
`tune2fs -U ${UUID_RESTORE} /dev/loop0p2`
`tune2fs -U ${UUID_ROOTFS} /dev/loop0p3`

(As build environment, I'm using Alpine Linux OS 3.8 installed from scratch with only necessary packages in current versions.)

Looking forward to the updates.
Thanks for all your efforts!

**Comment by tolland** [comment]
Hmm.. I'm currently running into [this issue](https://github.com/raspberrypi/linux/issues/2408#issuecomment-423519126) with the current raspbian image, it's causing the rpi to lock up when the image is restored requiring manual intervention. There appears to be a patch merged, but it's not in the downloadable image.

**Comment by tolland** [comment]
I finally got around to looking at it, this uses the new image;
https://github.com/limepepper/ansible-role-raspberrypi/tree/adding-inspecting-sfdisk-for-partition-size

**Comment by K3rm1t4** [comment]
Good stuff, thanks very much!
I'll test it out once time permits.

Some early feedback though after a first glance at the new code:
1. I think you'd want to put `$BASE` in here :wink:
`sudo fdisk -l 2018-06-27-raspbian-stretch-lite.img | grep 'Sector size'`

2. I guess the checksum verification for the downloaded image file is still a work in progress, right? :relaxed:
`raspian_lite_06_27_sha256=3271b244734286d99aeba8fa043b6634cad488d211583814a2018fc14fdca313`

3. Did you have time to check if this modification works in your build OS also and could be universally used?
> At least tune2fs version 1.44.2 (14-May-2018) seems to have issues with syntax of commands [#103](https://github.com/limepepper/ansible-role-raspberrypi/blob/74020a705f7d7d65414d2e2bfbdbfe638059bb90/files/create-factory-reset#L103) and [#104](https://github.com/limepepper/ansible-role-raspberrypi/blob/74020a705f7d7d65414d2e2bfbdbfe638059bb90/files/create-factory-reset#L104), expecting partition information as the last argument now:
> `tune2fs -U ${UUID_RESTORE} /dev/loop0p2`
> `tune2fs -U ${UUID_ROOTFS} /dev/loop0p3`
> 
> (As build environment, I'm using Alpine Linux OS 3.8 installed from scratch with only necessary packages in current versions.)

**Comment by tolland** [comment]
I've pushed some more changes, which use a generated loopback device name and fix those other hard coded values.

I have a list of other things that I'd like to implement. e.g. the recovery img size is statically set, and I might as well get that from the known partition sizes of pt+boot+recoveryfs+rootfs

**Comment by tolland** [comment]
This issue is out of date now, will open a new issue for recent releases of Pi OS
